# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calender_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_synced',
            field=models.BooleanField(default=False),
        ),
    ]
